cabbage/config/routes.rb
# Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
Rails.application.routes.draw do
  # alternative matching host: "exp.lvlup.pro"
  # https://guides.rubyonrails.org/routing.html#restricting-the-routes-created
  # https://guides.rubyonrails.org/routing.html#advanced-constraints
  # https://blog.appsignal.com/2020/03/04/building-a-rails-app-with-multiple-subdomains.html
  # https://stackoverflow.com/questions/6054668/rails-3-routing-and-multiple-domains/6058737#6058737

  # TODO use config / env for domains
  %w[lvlup.pro localhost].each { |domain|
    constraints domain: domain do
      devise_for :users, as: "devise_"+domain.gsub(".","_")
      resources :websites
      resources :domains
      resources :pages
      match '/p/:website/' => 'pages#page_by_slug', via: :get, as: "match_website_root_"+domain.gsub(".","_")
      match '/p/:website/*path' => 'pages#page_by_slug', via: :get, as: "match_website_path_"+domain.gsub(".","_")
    end
  }

  # TODO ignore panel domains to skip DB query
  root :to => "pages#page_by_slug_and_domain"
  match '*path' => 'pages#page_by_slug_and_domain', via: :get
end

cabbage/app/models/website.rb
class Website < ApplicationRecord
  belongs_to :user
  has_many :domains
  has_many :pages
end

cabbage/app/controllers/websites_controller.rb
class WebsitesController < ApplicationController
  before_action :set_website, only: %i[ show edit update destroy ]

  # GET /s/<slug>
  def site
    puts request.domain
    puts request.subdomain
    puts request.host
    @website = Website.find_by_slug(request.subdomain)
    @website = Website.find_by_slug("example") unless @website
  end

  # GET /websites or /websites.json
  def index
    @websites = Website.all
  end

  # GET /websites/1 or /websites/1.json
  def show
  end

  # GET /websites/new
  def new
    @website = Website.new
  end

  # GET /websites/1/edit
  def edit
  end

  # POST /websites or /websites.json
  def create
    @website = Website.new(website_params)

    respond_to do |format|
      if @website.save
        format.html { redirect_to website_url(@website), notice: "Website was successfully created." }
        format.json { render :show, status: :created, location: @website }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @website.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /websites/1 or /websites/1.json
  def update
    respond_to do |format|
      if @website.update(website_params)
        format.html { redirect_to website_url(@website), notice: "Website was successfully updated." }
        format.json { render :show, status: :ok, location: @website }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @website.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /websites/1 or /websites/1.json
  def destroy
    @website.destroy

    respond_to do |format|
      format.html { redirect_to websites_url, notice: "Website was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_website
      @website = Website.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def website_params
      params.require(:website).permit(:user_id, :name, :slug, :disabled_until, :abuse, :body)
    end
end

cabbage/app/helpers/websites_helper.rb
module WebsitesHelper
end

cabbage/app/views/websites/_form.html.erb
<%= form_with(model: website, class: "contents") do |form| %>
  <% if website.errors.any? %>
    <div id="error_explanation" class="bg-red-50 text-red-500 px-3 py-2 font-medium rounded-lg mt-3">
      <h2><%= pluralize(website.errors.count, "error") %> prohibited this website from being saved:</h2>

      <ul>
        <% website.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="my-5">
    <%= form.label :user_id %>
    <%= form.text_field :user_id, class: "block shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2 w-full" %>
  </div>

  <div class="my-5">
    <%= form.label :name %>
    <%= form.text_field :name, class: "block shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2 w-full" %>
  </div>

  <div class="my-5">
    <%= form.label :slug %>
    <%= form.text_field :slug, class: "block shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2 w-full" %>
  </div>

  <div class="my-5">
    <%= form.label :disabled_until %>
    <%= form.datetime_field :disabled_until, class: "block shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2 w-full" %>
  </div>

  <div class="my-5">
    <%= form.label :abuse %>
    <%= form.check_box :abuse, class: "block mt-2 h-5 w-5" %>
  </div>

  <div class="my-5">
    <%= form.label :body %>
    <%= form.text_field :body, class: "block shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2 w-full" %>
  </div>

  <div class="inline">
    <%= form.submit class: "rounded-lg py-3 px-5 bg-blue-600 text-white inline-block font-medium cursor-pointer" %>
  </div>
<% end %>

cabbage/app/views/websites/_website.html.erb
<div id="<%= dom_id website %>">
  <p class="my-5">
    <strong class="block font-medium mb-1">User:</strong>
    <%= website.user_id %>
  </p>

  <p class="my-5">
    <strong class="block font-medium mb-1">Name:</strong>
    <%= website.name %>
  </p>

  <p class="my-5">
    <strong class="block font-medium mb-1">Slug:</strong>
    <%= website.slug %>
  </p>

  <p class="my-5">
    <strong class="block font-medium mb-1">Disabled until:</strong>
    <%= website.disabled_until %>
  </p>

  <p class="my-5">
    <strong class="block font-medium mb-1">Abuse:</strong>
    <%= website.abuse %>
  </p>

  <p class="my-5">
    <strong class="block font-medium mb-1">Body:</strong>
    <%= website.body %>
  </p>

  <% if action_name != "show" %>
    <%= link_to "Show this website", website, class: "rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
    <%= link_to 'Edit this website', edit_website_path(website), class: "rounded-lg py-3 ml-2 px-5 bg-gray-100 inline-block font-medium" %>
    <hr class="mt-6">
  <% end %>
</div>

cabbage/app/views/websites/edit.html.erb
<div class="mx-auto md:w-2/3 w-full">
  <h1 class="font-bold text-4xl">Editing website</h1>

  <%= render "form", website: @website %>

  <%= link_to "Show this website", @website, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
  <%= link_to "Back to websites", websites_path, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
</div>

cabbage/app/views/websites/index.html.erb
<div class="w-full">
  <% if notice.present? %>
    <p class="py-2 px-3 bg-green-50 mb-5 text-green-500 font-medium rounded-lg inline-block" id="notice"><%= notice %></p>
  <% end %>

  <div class="flex justify-between items-center">
    <h1 class="font-bold text-4xl">Websites</h1>
    <%= link_to 'New website', new_website_path, class: "rounded-lg py-3 px-5 bg-blue-600 text-white block font-medium" %>
  </div>

  <div id="websites" class="min-w-full">
    <%= render @websites %>
  </div>
</div>

cabbage/app/views/websites/new.html.erb
<div class="mx-auto md:w-2/3 w-full">
  <h1 class="font-bold text-4xl">New website</h1>

  <%= render "form", website: @website %>

  <%= link_to 'Back to websites', websites_path, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
</div>

cabbage/app/views/websites/show.html.erb
<div class="mx-auto md:w-2/3 w-full flex">
  <div class="mx-auto">
    <% if notice.present? %>
      <p class="py-2 px-3 bg-green-50 mb-5 text-green-500 font-medium rounded-lg inline-block" id="notice"><%= notice %></p>
    <% end %>

    <%= render @website %>

    <%= link_to 'Edit this website', edit_website_path(@website), class: "mt-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
    <div class="inline-block ml-2">
      <%= button_to 'Destroy this website', website_path(@website), method: :delete, class: "mt-2 rounded-lg py-3 px-5 bg-gray-100 font-medium" %>
    </div>
    <%= link_to 'Back to websites', websites_path, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
  </div>
</div>

cabbage/app/views/websites/slugs.html.erb
<%= @page.body %>