cabbage/config/routes.rb
# Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
Rails.application.routes.draw do
  # alternative matching host: "exp.lvlup.pro"
  # https://guides.rubyonrails.org/routing.html#restricting-the-routes-created
  # https://guides.rubyonrails.org/routing.html#advanced-constraints
  # https://blog.appsignal.com/2020/03/04/building-a-rails-app-with-multiple-subdomains.html
  # https://stackoverflow.com/questions/6054668/rails-3-routing-and-multiple-domains/6058737#6058737

  # TODO use config / env for domains
  %w[lvlup.pro localhost].each { |domain|
    constraints domain: domain do
      devise_for :users, as: "devise_"+domain.gsub(".","_")
      resources :websites
      resources :domains
      resources :pages
      match '/p/:website/' => 'pages#page_by_slug', via: :get, as: "match_website_root_"+domain.gsub(".","_")
      match '/p/:website/*path' => 'pages#page_by_slug', via: :get, as: "match_website_path_"+domain.gsub(".","_")
    end
  }

  # TODO ignore panel domains to skip DB query
  root :to => "pages#page_by_slug_and_domain"
  match '*path' => 'pages#page_by_slug_and_domain', via: :get
end

cabbage/app/models/domain.rb
class Domain < ApplicationRecord
  belongs_to :user
  belongs_to :website, optional: true
end

cabbage/app/controllers/domains_controller.rb
class DomainsController < ApplicationController
  before_action :set_domain, only: %i[ show edit update destroy ]

  # GET /domains or /domains.json
  def index
    @domains = Domain.all
  end

  # GET /domains/1 or /domains/1.json
  def show
  end

  # GET /domains/new
  def new
    @domain = Domain.new
  end

  # GET /domains/1/edit
  def edit
  end

  # POST /domains or /domains.json
  def create
    @domain = Domain.new(domain_params)

    respond_to do |format|
      if @domain.save
        format.html { redirect_to domain_url(@domain), notice: "Domain was successfully created." }
        format.json { render :show, status: :created, location: @domain }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @domain.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /domains/1 or /domains/1.json
  def update
    respond_to do |format|
      if @domain.update(domain_params)
        format.html { redirect_to domain_url(@domain), notice: "Domain was successfully updated." }
        format.json { render :show, status: :ok, location: @domain }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @domain.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /domains/1 or /domains/1.json
  def destroy
    @domain.destroy

    respond_to do |format|
      format.html { redirect_to domains_url, notice: "Domain was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_domain
      @domain = Domain.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def domain_params
      params.require(:domain).permit(:name, :user_id, :website_id)
    end
end

cabbage/app/helpers/domains_helper.rb
module DomainsHelper
end

cabbage/app/views/domains/_domain.html.erb
<div id="<%= dom_id domain %>">
  <p class="my-5">
    <strong class="block font-medium mb-1">Name:</strong>
    <%= domain.name %>
  </p>

  <p class="my-5">
    <strong class="block font-medium mb-1">User:</strong>
    <%= domain.user_id %>
  </p>

  <p class="my-5">
    <strong class="block font-medium mb-1">Website:</strong>
    <%= domain.website_id %>
  </p>

  <% if action_name != "show" %>
    <%= link_to "Show this domain", domain, class: "rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
    <%= link_to 'Edit this domain', edit_domain_path(domain), class: "rounded-lg py-3 ml-2 px-5 bg-gray-100 inline-block font-medium" %>
    <hr class="mt-6">
  <% end %>
</div>

cabbage/app/views/domains/_form.html.erb
<%= form_with(model: domain, class: "contents") do |form| %>
  <% if domain.errors.any? %>
    <div id="error_explanation" class="bg-red-50 text-red-500 px-3 py-2 font-medium rounded-lg mt-3">
      <h2><%= pluralize(domain.errors.count, "error") %> prohibited this domain from being saved:</h2>

      <ul>
        <% domain.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="my-5">
    <%= form.label :name %>
    <%= form.text_field :name, class: "block shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2 w-full" %>
  </div>

  <div class="my-5">
    <%= form.label :user_id %>
    <%= form.text_field :user_id, class: "block shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2 w-full" %>
  </div>

  <div class="my-5">
    <%= form.label :website_id %>
    <%= form.text_field :website_id, class: "block shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2 w-full" %>
  </div>

  <div class="inline">
    <%= form.submit class: "rounded-lg py-3 px-5 bg-blue-600 text-white inline-block font-medium cursor-pointer" %>
  </div>
<% end %>

cabbage/app/views/domains/edit.html.erb
<div class="mx-auto md:w-2/3 w-full">
  <h1 class="font-bold text-4xl">Editing domain</h1>

  <%= render "form", domain: @domain %>

  <%= link_to "Show this domain", @domain, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
  <%= link_to "Back to domains", domains_path, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
</div>

cabbage/app/views/domains/index.html.erb
<div class="w-full">
  <% if notice.present? %>
    <p class="py-2 px-3 bg-green-50 mb-5 text-green-500 font-medium rounded-lg inline-block" id="notice"><%= notice %></p>
  <% end %>

  <div class="flex justify-between items-center">
    <h1 class="font-bold text-4xl">Domains</h1>
    <%= link_to 'New domain', new_domain_path, class: "rounded-lg py-3 px-5 bg-blue-600 text-white block font-medium" %>
  </div>

  <div id="domains" class="min-w-full">
    <%= render @domains %>
  </div>
</div>

cabbage/app/views/domains/new.html.erb
<div class="mx-auto md:w-2/3 w-full">
  <h1 class="font-bold text-4xl">New domain</h1>

  <%= render "form", domain: @domain %>

  <%= link_to 'Back to domains', domains_path, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
</div>

cabbage/app/views/domains/show.html.erb
<div class="mx-auto md:w-2/3 w-full flex">
  <div class="mx-auto">
    <% if notice.present? %>
      <p class="py-2 px-3 bg-green-50 mb-5 text-green-500 font-medium rounded-lg inline-block" id="notice"><%= notice %></p>
    <% end %>

    <%= render @domain %>

    <%= link_to 'Edit this domain', edit_domain_path(@domain), class: "mt-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
    <div class="inline-block ml-2">
      <%= button_to 'Destroy this domain', domain_path(@domain), method: :delete, class: "mt-2 rounded-lg py-3 px-5 bg-gray-100 font-medium" %>
    </div>
    <%= link_to 'Back to domains', domains_path, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
  </div>
</div>